[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  [[headers.values]]
    key = "Cache-Control"
    value = "max-age=0, no-cache, no-store, must-revalidate"
  
  [[headers.values]]
    key = "Content-Type"
    value = "application/javascript"
    for = "/*.js"
